on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
    - name: Build
      run: docker build --target build .
    - name: Test
      run: docker build --target test .

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    - name: Restore
      run: dotnet restore test/StrEnum.Npgsql.IntegrationTests/StrEnum.Npgsql.IntegrationTests.csproj
    - name: Build
      run: dotnet build test/StrEnum.Npgsql.IntegrationTests/StrEnum.Npgsql.IntegrationTests.csproj -c Release --no-restore
    - name: Test
      run: dotnet test test/StrEnum.Npgsql.IntegrationTests/StrEnum.Npgsql.IntegrationTests.csproj -c Release --no-build --logger "console;verbosity=normal"
